### ISSUE TITLE
Names must be unique

### ISSUE THREAD

**Issue by soggybag** [soggybag/course-book-react#5]
Names of students and courses should be unique. Currently the app checks for a match but it's not a case sensitive match. 

- If you added the 'Joe' and 'Joe' was already in a list it would be rejected. 
- If you add the name 'joe' and the name 'Joe' was in the list this would be allowed. 

The same is true for course names. 

Your goal is to check the case of a new student or course name. Currently names are trimmed of white space. Names should keep case but checked for match regardless of case.

**Comment by vivianedias** [comment]
Hi, @soggybag . I'd really like to solve this issue :)

**Comment by soggybag** [comment]
It’s all yours go for it!

**Comment by jamiejamiebobamie** [comment]
I'm going to tackle this one too.

**Comment by soggybag** [comment]
Go for it!

**Comment by soggybag** [comment]
Closed.
